version: 1.19.0.{build}
image: Visual Studio 2019
platform: Any CPU
configuration: Release
environment:
    PROJECT_NAME:   'Cube.Core'
    PROJECT_MAIN:   'Cube.Core'
    PROJECT_BIN:    'bin\%PLATFORM%\%CONFIGURATION%\net45'
    PROJECT_LIB:    '..\packages'
    TEST_TOOL:      '$(PROJECT_LIB)\OpenCover\4.7.922\tools\OpenCover.Console.exe'
    TEST_CORETOOL:  'dotnet.exe'
    TEST_ARGS:      'test --logger:Appveyor'
    TEST_FILTERS:   '+[Cube*]* -[*]*NativeMethods -[*]*Properties.*'
    TEST_COVERAGE:  'CoverResults.xml'
    TEST_LOG:       'TestResults'
branches:
    only:
        - master
skip_tags: true
nuget:
    project_feed: true
    disable_publish_on_pr: true
clone_folder: 'C:\Cube\%PROJECT_NAME%'
before_build:
    - dotnet restore "%PROJECT_MAIN%.sln"
build:
    project: '%PROJECT_MAIN%.sln'
    parallel: true
    publish_nuget: true
    verbosity: minimal
test_script:
    - >
      "%TEST_TOOL%"
      -log:Error
      -register:appveyor
      -target:"%TEST_CORETOOL%"
      -targetargs:"%TEST_ARGS%"
      -returntargetcode
      -hideskipped:All
      -output:"%TEST_COVERAGE%"
      -filter:"%TEST_FILTERS%"
after_test:
    - pip install codecov
    - codecov -f "%TEST_COVERAGE%"
    - xcopy /q /Y /I "Tests\%PROJECT_BIN%\*.log" "%TEST_LOG%\"
    - xcopy /q /Y /I "%TEST_COVERAGE%" "%TEST_LOG%\"
artifacts:
    - path: '%TEST_LOG%'
