version: 1.15.0.{build}
image: Visual Studio 2019 Preview
platform: Any CPU
configuration: Release
environment:
    PROJECT_NAME:  "Cube.FileSystem"
    PROJECT_BIN:   "bin\\%PLATFORM%\\%CONFIGURATION%\\net45"
    TEST_TOOL:     "..\\packages\\OpenCover\\4.7.922\\tools\\OpenCover.Console.exe"
    TEST_CORETOOL: "nunit3-console.exe"
    TEST_RESULTS:  "TestResults"
    TEST_COVERAGE: "CoverResults.xml"
branches:
    only:
        - master
skip_tags: true
nuget:
    project_feed: true
    disable_publish_on_pr: true
clone_folder: "C:\\Cube\\%PROJECT_NAME%"
before_build:
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget restore "%PROJECT_NAME%.sln"
build:
    project: "%PROJECT_NAME%.sln"
    parallel: true
    publish_nuget: true
    verbosity: minimal
test_script:
    - >
      "%TEST_TOOL%"
      -log:Error
      -register:user
      -target:"%TEST_CORETOOL%"
      -targetargs:"%PROJECT_NAME%.Tests.dll"
      -targetdir:"Tests\%PROJECT_BIN%"
      -returntargetcode
      -hideskipped:All
      -output:"%TEST_COVERAGE%"
      -filter:"+[Cube*]* -[*]*NativeMethods -[*]*Properties.*"
after_test:
    - xcopy /q /Y /I "Tests\%PROJECT_BIN%\*.log" "%TEST_RESULTS%\"
    - xcopy /q /Y /I "%TEST_COVERAGE%" "%TEST_RESULTS%\"
    - pip install codecov
    - codecov -f "%TEST_COVERAGE%"
artifacts:
    - path: "%TEST_RESULTS%"
