trigger:
    - master
pool:
    vmImage: 'VS2017-Win2016'
variables:
    PROJECT_NAME:     'Cube.Core'
    PROJECT_PLATFORM: 'Any CPU'
    PROJECT_CONFIG:   'Release'
    PROJECT_BIN:      'bin\Any CPU\Release\net45'
    TEST_TOOL:        '..\packages\OpenCover\4.7.922\tools\OpenCover.Console.exe'
    TEST_CORETOOL:    '..\packages\NUnit.ConsoleRunner\3.10.0\tools\nunit3-console.exe'
    TEST_RESULT:      'TestResult.xml'
    TEST_COVERAGE:    'CoverResults.xml'
    TEST_LOGS:        'TestResults'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '>= 3.7'
    architecture: 'x64'
  displayName: 'Use Python 3.7 or later'

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '>= 4.9'
  displayName: 'Use NuGet 4.9 or later'

- script: |
    nuget restore "$(PROJECT_NAME).sln"
  displayName: 'Restore NuGet packages'

- task: VSBuild@1
  inputs:
    solution: '$(PROJECT_NAME).sln'
    platform: '$(PROJECT_PLATFORM)'
    configuration: '$(PROJECT_CONFIG)'
  displayName: 'Build solution'

- script: >-
    "$(TEST_TOOL)"
    -log:Error
    -register:user
    -target:"$(TEST_CORETOOL)"
    -targetargs:"$(PROJECT_NAME).Tests.dll"
    -targetdir:"Tests\$(PROJECT_BIN)"
    -returntargetcode
    -hideskipped:All
    -output:"$(TEST_COVERAGE)"
    -filter:"+[Cube*]* -[*]*NativeMethods -[*]*Properties.*"
  displayName: 'Run tests via OpenCover and NUnit'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**\$(TEST_RESULT)'
  displayName: 'Publish test results'

- script: |
    pip install codecov
    codecov -f "$(TEST_COVERAGE)" -t $(CODECOV_TOKEN)
  displayName: "Send coverage results to Codecov"

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'Libraries\$(PROJECT_NAME).csproj'
    configuration: '$(PROJECT_CONFIG)'
  displayName: 'Create NuGet package'

- task: CopyFiles@2
  inputs:
    contents: '**\*.log'
    targetFolder: '$(TEST_LOGS)'
    overWrite: true
  displayName: 'Copy log files'

- task: CopyFiles@2
  inputs:
    contents: '**\$(TEST_RESULT)'
    targetFolder: '$(TEST_LOGS)'
    overWrite: true
  displayName: 'Copy test results'

- task: CopyFiles@2
  inputs:
    contents: '$(TEST_COVERAGE)'
    targetFolder: '$(TEST_LOGS)'
    overWrite: true
  displayName: 'Copy coverage results'

- task: ArchiveFiles@2
  inputs:
    archiveFile: '$(Build.ArtifactStagingDirectory)\$(TEST_LOGS).zip'
    rootFolderOrFile: '$(TEST_LOGS)'
    archiveType: 'zip'
    includeRootFolder: true
    replaceExistingArchive: true
  displayName: 'Archive test results'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: '$(PROJECT_NAME)'
    targetPath: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Publish pipline artifacts'
